//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public short IDField { get; set; }
        public Nullable<short> IDBoard { get; set; }
        public short IDFieldType { get; set; }
        public Nullable<short> IDUnit { get; set; }
        public sbyte X { get; set; }
        public sbyte Y { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual FieldType FieldType { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
