//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldType
    {
        public FieldType()
        {
            this.Field = new HashSet<Field>();
        }
    
        public short IDFieldType { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Field> Field { get; set; }
    }
}
