//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Board = new HashSet<Board>();
            this.User = new HashSet<User>();
        }
    
        public short IDGame { get; set; }
    
        public virtual ICollection<Board> Board { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
