//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitType
    {
        public UnitType()
        {
            this.Unit = new HashSet<Unit>();
        }
    
        public short IDUnitType { get; set; }
        public string Name { get; set; }
        public short Stamina { get; set; }
        public short Damage { get; set; }
        public short Move { get; set; }
    
        public virtual ICollection<Unit> Unit { get; set; }
    }
}
