//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Field = new HashSet<Field>();
        }
    
        public short IDUnit { get; set; }
        public short IDUnitType { get; set; }
        public Nullable<short> IDUser { get; set; }
    
        public virtual ICollection<Field> Field { get; set; }
        public virtual UnitType UnitType { get; set; }
        public virtual User User { get; set; }
    }
}
